import { Volume2, VolumeX, Wind, Bird } from 'lucide-react'
import type { FlightRuntime, FlightSnapshot } from '../FlightRuntime'
export function NaturePanel({ runtime, snapshot, locale }: { runtime: FlightRuntime; snapshot: FlightSnapshot; locale: 'en' | 'zh-CN' }) {
 const zh = locale === 'zh-CN', sound = runtime.soundscape.getSnapshot()
 return <div className="flight-nature">
  <div className="flight-sound-choice"><div><span className="flight-control-title">{sound.enabled ? <Volume2 size={18} aria-hidden="true"/> : <VolumeX size={18} aria-hidden="true"/>}{zh ? '听见海岸' : 'Listen to the coast'}</span><small>{zh ? '风、海浪和雨声，随位置轻轻变化' : 'Wind, waves and rain change gently with your view'}</small></div><button type="button" aria-label={sound.status==='retry'?(zh?'重试自然声音':'Retry nature sounds'):sound.enabled?(zh?'关闭自然声音':'Turn off nature sounds'):(zh?'开启自然声音':'Enable nature sounds')} className={sound.enabled ? '' : 'flight-sound-enable'} onClick={() => { if (sound.status === 'retry' || !sound.enabled) void runtime.enableSound(); else runtime.disableSound() }}>{sound.status === 'retry' ? (zh ? '重试' : 'Retry') : sound.enabled ? (zh ? '关闭' : 'Off') : (zh ? '开启' : 'On')}</button></div>
  <p className="flight-nature-status" role="status">{sound.status === 'loading' ? (zh ? '声音正在准备' : 'Preparing sounds') : sound.status === 'retry' ? (zh ? '声音暂时不可用，可以重试' : 'Sounds unavailable. You can retry.') : sound.enabled ? (zh ? '暂停或离开时，声音也会停下' : 'Sound stops when you pause or leave') : (zh ? '默认安静，只在你点击后开启' : 'Quiet by default. Starts only when you choose.')}</p>
  {sound.enabled && <label className="flight-light-range">{zh ? '声音音量' : 'Sound volume'}<input type="range" aria-label={zh ? '声音音量' : 'Sound volume'} min="0" max="1" step="0.05" value={sound.volume} onChange={event => runtime.setSoundVolume(Number(event.target.value))}/></label>}
  <label className="flight-setting flight-nature-toggle"><span><span className="flight-control-title"><Wind size={18} aria-hidden="true"/>{zh ? '植被微风' : 'Vegetation breeze'}</span><small>{zh ? '让树冠和低矮的叶子轻轻摇动' : 'A little movement in the canopy and low leaves'}</small></span><input type="checkbox" aria-label={zh ? '植被微风' : 'Vegetation breeze'} checked={runtime.livingIntent.wind} onChange={event => runtime.setLivingIntent('wind', event.target.checked)}/></label>
  <label className="flight-setting flight-nature-toggle"><span><span className="flight-control-title"><Bird size={18} aria-hidden="true"/>{zh ? '同类同行' : 'Flying companions'}</span><small>{zh ? '偶尔短暂同行 · 艺术化表现' : 'Occasional company · artistic interpretation'}</small></span><input type="checkbox" aria-label={zh ? '同类同行' : 'Flying companions'} checked={runtime.livingIntent.companions} onChange={event => runtime.setLivingIntent('companions', event.target.checked)}/></label>
  {runtime.livingIntent.companions && <p className="flight-nature-status" role="status">{snapshot.companions?.status === 'degraded' ? (zh ? '同伴暂时没有准备好，可关闭后重新开启' : 'Companions could not load. Turn off and on to retry.') : snapshot.companions?.status === 'loading' ? (zh ? '同伴正在准备' : 'Preparing companions') : (zh ? '它们有自己的航向，会从远处经过' : 'They follow their own course and pass in the distance')}</p>}
 </div>
}
