import { clockPolicy } from '../../src/flight-experience/environment/environment-clock'
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import { act, fireEvent, render, screen, waitFor } from '@testing-library/react'
import { BoxGeometry, Group, Mesh, MeshBasicMaterial, Texture, TextureLoader } from 'three'
import { FlightExperience } from '../../src/flight-experience/FlightExperience'
import type { FlightRuntime } from '../../src/flight-experience/FlightRuntime'
import { HorizonTerrain } from '../../src/flight-experience/horizon-terrain'
import { TerrainStream } from '../../src/flight-experience/terrain-stream'
import { I18nProvider } from '../../src/i18n/I18nProvider'
import type { ViewerController, ViewerModelDescriptor, StagedViewerModel } from '../../src/viewer/ViewerController'

class IdleWorker { postMessage() {} terminate() {} }
beforeEach(() => {
 vi.stubGlobal('Worker', IdleWorker)
 vi.spyOn(HorizonTerrain.prototype,'ready','get').mockReturnValue(true)
 vi.spyOn(TextureLoader.prototype, 'loadAsync').mockResolvedValue(new Texture())
 vi.spyOn(TerrainStream.prototype, 'previewReady', 'get').mockReturnValue(true)
 vi.spyOn(TerrainStream.prototype, 'ready', 'get').mockReturnValue(true)
 vi.spyOn(HTMLCanvasElement.prototype, 'getContext').mockImplementation((() => ({drawImage() {},getImageData: (_x:number,_y:number,w:number,h:number)=>({data:new Uint8ClampedArray(w*h*4)})})) as unknown as typeof HTMLCanvasElement.prototype.getContext)
})
afterEach(() => { vi.restoreAllMocks(); vi.unstubAllGlobals() })
async function mount() {
 const instances: FlightRuntime[] = []
 const root = new Group(), group = new Group(); group.add(root); root.add(new Mesh(new BoxGeometry(7,1,2),new MeshBasicMaterial()))
 const controller = {
  acquireExternalExperience: (runtime:FlightRuntime) => { instances.push(runtime); return {invalidate:vi.fn(),release:()=>runtime.dispose()} },
  stageModel: () => Promise.resolve({group,modelRoot:root,mixer:null,action:null,disposed:false} as unknown as StagedViewerModel),
  disposeStagedModel:vi.fn(),
 } as unknown as ViewerController
 const descriptor={} as ViewerModelDescriptor, onClose=vi.fn()
 const element=<I18nProvider initialState={{locale:'en',preference:'en'}}><FlightExperience controller={controller} descriptor={descriptor} onClose={onClose}/></I18nProvider>
 const view=render(element)
 await waitFor(()=>expect(instances).toHaveLength(1))
 const runtime=instances[0]!
 // Allow the actual asynchronous model/material attach to finish.
 await waitFor(()=>expect(runtime.pose.children).toHaveLength(1))
 act(()=>{runtime.update(0);runtime.completedFrame(document.createElement('canvas'))})
 return {runtime,instances,view,element,onClose}
}
describe('whole FlightExperience events with the actual Runtime (GPU/worker readiness stubbed)',()=>{
 it('keeps a visible but unfocused model load within its active budget',async()=>{
  let resolveModel:((model:StagedViewerModel)=>void)|undefined
  let runtime:FlightRuntime|undefined
  const controller={
   acquireExternalExperience:(instance:FlightRuntime)=>{runtime=instance;return {invalidate:vi.fn(),release:()=>instance.dispose()}},
   stageModel:()=>new Promise<StagedViewerModel>(resolve=>{resolveModel=resolve}),
   disposeStagedModel:vi.fn(),
  } as unknown as ViewerController
  const view=render(<I18nProvider initialState={{locale:'en',preference:'en'}}><FlightExperience controller={controller} descriptor={{} as ViewerModelDescriptor} onClose={vi.fn()}/></I18nProvider>)
  try{
   await waitFor(()=>expect(runtime).toBeDefined())
   const instance=runtime!
   await act(async()=>{await Promise.resolve()})
   let now=instance.preparation.startedAt
   vi.spyOn(performance,'now').mockImplementation(()=>now)
   fireEvent(window,new Event('focus'))
   now+=5000
   fireEvent(window,new Event('blur'))
   now+=10000
   expect(instance.preparation.tick(now)).toBe(false)
   expect(instance.preparation.snapshot().activeElapsed).toBeGreaterThanOrEqual(15000)
   expect(instance.preparation.snapshot().activeElapsed).toBeLessThan(15100)
   expect(instance.running).toBe(true)
   const root=new Group(),group=new Group();group.add(root);root.add(new Mesh(new BoxGeometry(7,1,2),new MeshBasicMaterial()))
   await act(async()=>{resolveModel?.({group,modelRoot:root,mixer:null,action:null,disposed:false} as unknown as StagedViewerModel);await Promise.resolve()})
   act(()=>{instance.update(0);instance.completedFrame(document.createElement('canvas'))})
   expect(instance.getSnapshot().reason).not.toBe('error')
   expect(instance.preparation.snapshot().activeElapsed).toBeLessThan(20000)
  }finally{view.unmount()}
 })
 it('recovers a genuinely unsafe displayed camera and still requires an explicit resume',async()=>{
  const {runtime,view}=await mount()
  await waitFor(()=>expect(screen.getByRole('dialog')).toHaveAttribute('data-flight-phase','ready'))
  vi.spyOn(runtime.terrain,'displayedHeight').mockReturnValue(0)
  vi.spyOn(runtime.terrain,'safeToEnter').mockReturnValue(true)
  act(()=>runtime.start())
  act(()=>runtime.update(0))
  const hero=runtime.simulation.renderState().position
  runtime.camera.position.set(hero.x,hero.y,hero.z)
  act(()=>runtime.update(1/60))
  expect(runtime.getSnapshot()).toMatchObject({phase:'paused',reason:'camera'})
  expect(runtime.canResume).toBe(false)
  act(()=>{runtime.resize(1280,720);runtime.update(0)})
  expect(runtime.cameraRig.rejection).toBeNull()
  expect(runtime.getSnapshot()).toMatchObject({phase:'paused',reason:null})
  expect(screen.getByRole('button',{name:'Continue flying'})).toBeVisible()
  runtime.simulation.safetyStop=true
  expect(runtime.canResume).toBe(false)
  runtime.simulation.safetyStop=false
  fireEvent.click(screen.getByRole('button',{name:'Continue flying'}))
  expect(runtime.getSnapshot().phase).toBe('flying')
  view.unmount()
 })
 it('preserves live zoom when quality changes and leaves a new starting place pending',async()=>{
  const {runtime,view}=await mount()
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  fireEvent.click(screen.getByRole('tab',{name:'Flight'}))
  fireEvent.click(screen.getByText('Flight & display settings'))
  fireEvent.click(screen.getByRole('button',{name:'Fast'}))
  fireEvent.change(screen.getByRole('slider',{name:'Camera distance'}),{target:{value:'1.5'}})
  expect(runtime.getSnapshot().settings.zoom).toBe(1.5)
  fireEvent.click(screen.getByRole('button',{name:'Standard'}))
  expect(runtime.getSnapshot().settings.zoom).toBe(1.5)
  expect(screen.getByRole('slider',{name:'Camera distance'})).toHaveValue('1.5')
  const position={...runtime.simulation.position}
  fireEvent.click(screen.getByRole('tab',{name:'Views'}))
  fireEvent.click(screen.getByText('Choose a new starting point'))
  fireEvent.click(screen.getByRole('button',{name:/Valley/}))
  expect(runtime.simulation.position).toEqual(position)
  view.unmount()
 })
 it('offers camera presets, click nudges and focused keyboard without steering the animal',async()=>{
  const {runtime,view}=await mount()
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}));fireEvent.click(screen.getByRole('tab',{name:'Flight'}))
  const heading=runtime.simulation.heading,time=runtime.simulation.time,key=vi.spyOn(runtime.input,'key')
  fireEvent.click(screen.getByRole('button',{name:'In front'}))
  expect(runtime.cameraRig.perspective).toBe('front')
  fireEvent.click(screen.getByText('Adjust angle'))
  fireEvent.keyDown(screen.getByRole('button',{name:'Orbit left'}),{key:'ArrowLeft',code:'ArrowLeft'})
  expect(key).not.toHaveBeenCalled();expect(runtime.cameraRig.perspective).toBe('custom')
  fireEvent.click(screen.getByRole('button',{name:'View from above'}));expect(runtime.cameraRig.requested.pitch).toBeGreaterThan(0)
  expect(runtime.simulation.heading).toBe(heading);expect(runtime.simulation.time).toBe(time)
  expect(screen.queryByText('Where are we?')).not.toBeInTheDocument()
  act(()=>runtime.contextLost());expect(runtime.cameraRig.moving).toBe(false)
  act(()=>runtime.contextRestored());expect(runtime.getSnapshot().phase).toBe('paused')
  view.unmount()
 })
 it('dismisses settings on an outside press and preserves the first orbit drag',async()=>{
  const {runtime,view}=await mount()
  act(()=>runtime.start());act(()=>runtime.pause())
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  const layer=view.container.querySelector<HTMLElement>('.flight-camera-gesture')!
  expect(layer).not.toBeNull()
  layer.setPointerCapture=vi.fn();layer.hasPointerCapture=()=>false
  vi.spyOn(layer,'getBoundingClientRect').mockReturnValue({width:1000,height:700} as DOMRect)
  const orbit=vi.spyOn(runtime,'orbitCamera')
  const pointer=(type:string,x:number)=>{const event=new Event(type,{bubbles:true});Object.assign(event,{pointerId:1,pointerType:'mouse',button:0,buttons:1,clientX:x,clientY:200});fireEvent(layer,event)}
  pointer('pointerdown',200)
  expect(view.container.querySelector('#flight-settings-panel')).toBeNull()
  expect(view.container.querySelector('.flight-camera-gesture')).toBe(layer)
  pointer('pointermove',300);pointer('pointerup',300)
  expect(orbit).toHaveBeenCalled()
  view.unmount()
 })
 it('keeps the panel close control clear when the camera is away from behind',async()=>{
  const {runtime,view}=await mount()
  act(()=>runtime.selectPerspective('front'))
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  expect(screen.queryByRole('button',{name:'Back behind'})).not.toBeInTheDocument()
  fireEvent.click(screen.getByRole('button',{name:'Close settings'}))
  expect(screen.getByRole('button',{name:'Back behind'})).toBeVisible()
  view.unmount()
 })
 it('changes language from a portalled choice without dismissing the panel on pointer down',async()=>{
  const {runtime,view}=await mount()
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  fireEvent.click(screen.getByRole('button',{name:'Change language, current English'}))
  const choice=screen.getByRole('menuitemradio',{name:'简体中文'})
  fireEvent.pointerDown(choice,{pointerId:2,pointerType:'touch'})
  expect(screen.getByRole('tab',{name:'Scenery'})).toBeInTheDocument()
  fireEvent.click(choice)
  expect(document.documentElement.lang).toBe('zh-CN')
  expect(screen.getByRole('tab',{name:'风景'})).toBeVisible()
  expect(runtime.getSnapshot().phase).toBe('ready')
  view.unmount()
 })
 it('resumes after unlock even when Safari has not sent a window focus event',async()=>{
  const {runtime,view}=await mount()
  act(()=>{runtime.start();runtime.setVisibilityState(false);runtime.setVisibilityState(true);runtime.setFocusState(false)})
  expect(runtime.getSnapshot()).toMatchObject({phase:'paused',reason:'hidden'})
  expect(runtime.canResume).toBe(false)
  const resume=view.container.querySelector<HTMLButtonElement>('.flight-toolbar__right>button[aria-label="Continue flying"]')!
  expect(resume).not.toBeNull()
  expect(resume).toBeEnabled()
  fireEvent.click(resume)
  expect(runtime.getSnapshot().phase).toBe('flying')
  view.unmount()
 })
 it('restores camera touch input on the first scene gesture after unlock',async()=>{
  const {runtime,view}=await mount()
  act(()=>{runtime.start();runtime.setVisibilityState(false);runtime.setVisibilityState(true);runtime.setFocusState(false)})
  const layer=view.container.querySelector<HTMLElement>('.flight-camera-gesture')!
  expect(layer).not.toBeNull()
  const capture=vi.fn();layer.setPointerCapture=capture;layer.hasPointerCapture=()=>false
  vi.spyOn(layer,'getBoundingClientRect').mockReturnValue({width:400,height:800} as DOMRect)
  const orbit=vi.spyOn(runtime,'orbitCamera')
  const epoch=runtime.getSnapshot().cameraInputEpoch
  const pointer=(type:string,x:number)=>{const event=new Event(type,{bubbles:true});Object.assign(event,{pointerId:7,pointerType:'touch',button:0,buttons:1,clientX:x,clientY:200});fireEvent(layer,event)}
  pointer('pointerdown',80)
  expect(capture).toHaveBeenCalledWith(7)
  expect(runtime.presentationActive).toBe(true)
  expect(runtime.canObserveCamera).toBe(true)
  expect(runtime.getSnapshot().cameraInputEpoch).toBe(epoch)
  pointer('pointermove',130);pointer('pointerup',130)
  expect(orbit).toHaveBeenCalled()
  expect(runtime.cameraRig.perspective).toBe('custom')
  expect(runtime.getSnapshot().phase).toBe('paused')
  view.unmount()
 })
 it('resumes with one toolbar click while settings are open',async()=>{
  const {runtime,view}=await mount()
  act(()=>runtime.start());act(()=>runtime.pause())
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  fireEvent.click(screen.getByRole('button',{name:'Continue flying'}))
  expect(runtime.getSnapshot().phase).toBe('flying')
  expect(view.container.querySelector('#flight-settings-panel')).toBeNull()
  view.unmount()
 })
 it('keeps mode and movement on panel/rerender/language changes and isolates range keyboard shortcuts',async()=>{
  const {runtime,instances,view,element}=await mount()
  act(()=>runtime.start())
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  fireEvent.click(screen.getByRole('button',{name:'Auto'}))
  expect(runtime.environmentClock.solarMode).toBe('auto')
  expect(runtime.getSnapshot().phase).toBe('flying')
  const key=vi.spyOn(runtime.input,'key')
  fireEvent.click(screen.getByText('Fine-tune the light'))
  fireEvent.keyDown(screen.getByRole('slider'),{code:'ArrowRight',key:'ArrowRight'})
  expect(key).not.toHaveBeenCalled()
  view.rerender(element);expect(instances).toHaveLength(1)
  fireEvent.click(screen.getByRole('tab',{name:'Flight'}))
  fireEvent.click(screen.getByRole('button',{name:'Change language, current English'}))
  fireEvent.click(screen.getByRole('menuitemradio',{name:'简体中文'}))
  expect(instances).toHaveLength(1);expect(runtime.environmentClock.solarMode).toBe('auto')
  expect(runtime.getSnapshot().phase).toBe('flying')
  fireEvent.keyDown(window,{code:'Escape',key:'Escape'})
  expect(screen.getByRole('button',{name:'飞行与风景'})).toHaveFocus()
  expect(runtime.getSnapshot().phase).toBe('flying')
  view.unmount();expect(runtime.running).toBe(false)
 })
 it.each(['terrain','quality'])('retains ordinary %s preparation across hidden, focus and context overlap',async(kind)=>{
  const {runtime,view}=await mount()
  act(()=>runtime.start())
  vi.spyOn(TerrainStream.prototype,'ready','get').mockReturnValue(false)
  vi.spyOn(TerrainStream.prototype,'previewReady','get').mockReturnValue(false)
  act(()=>{if(kind==='quality')runtime.setQuality('balanced');else runtime.pause('terrain')})
  expect(runtime.getSnapshot().phase).toBe('buffering')
  const terrainUpdate=vi.spyOn(runtime.terrain,'update')
  const position={...runtime.simulation.position},motion=runtime.environmentClock.motionSeconds
  vi.spyOn(document,'hidden','get').mockReturnValue(true)
  fireEvent(document,new Event('visibilitychange'));fireEvent(window,new Event('blur'))
  act(()=>{runtime.contextLost();runtime.contextRestored();runtime.update(60)})
  expect(runtime.running).toBe(false)
  vi.spyOn(document,'hidden','get').mockReturnValue(false)
  fireEvent(document,new Event('visibilitychange'));expect(runtime.running).toBe(false)
  fireEvent(window,new Event('focus'))
  terrainUpdate.mockClear()
  act(()=>runtime.update(1/60))
  expect(terrainUpdate).toHaveBeenCalled()
  expect(runtime.getSnapshot().phase).toBe('paused')
  expect(runtime.canResume).toBe(false)
  vi.spyOn(TerrainStream.prototype,'previewReady','get').mockReturnValue(true)
  // Preview coverage alone must not discard unfinished safety preparation.
  act(()=>runtime.update(1/60))
  expect(runtime.running).toBe(true)
  vi.spyOn(TerrainStream.prototype,'ready','get').mockReturnValue(true)
  act(()=>runtime.update(1/60))
  expect(runtime.canResume).toBe(true)
  expect(runtime.getSnapshot().phase).toBe('paused')
  terrainUpdate.mockClear();act(()=>runtime.update(1/60))
  expect(terrainUpdate).not.toHaveBeenCalled()
  expect(runtime.simulation.position).toEqual(position)
  expect(runtime.environmentClock.motionSeconds).toBe(motion)
  view.unmount();act(()=>runtime.update(60));expect(runtime.running).toBe(false)
 })
 it.each(['entry','return'])('restores only necessary %s preparation after DOM hidden/focus events and preserves error UI',async(direction)=>{
  const {runtime,view,onClose}=await mount()
  act(()=>{runtime.enterViewpoint('seaward');if(direction==='return')runtime.returnFromViewpoint();runtime.setSolarDayProgress(.7);runtime.setSolarMode('auto')})
  vi.spyOn(document,'hidden','get').mockReturnValue(true)
  fireEvent(document,new Event('visibilitychange'));fireEvent(window,new Event('blur'))
  act(()=>{runtime.contextLost();runtime.contextRestored()})
  expect(runtime.running).toBe(false)
  vi.spyOn(document,'hidden','get').mockReturnValue(false)
  fireEvent(document,new Event('visibilitychange'));expect(runtime.running).toBe(false)
  fireEvent(window,new Event('focus'));expect(runtime.running).toBe(true)
  expect(runtime.observation.sceneryPaused).toBe(true)
  expect(runtime.getSnapshot().daylight?.status).toBe('suspended')
  vi.spyOn(console,'error').mockImplementation(()=>{})
  act(()=>runtime.fail(new Error('injected update fault')))
  expect(screen.getByRole('alert')).toBeVisible();expect(runtime.running).toBe(false)
  fireEvent(window,new Event('focus'));expect(runtime.running).toBe(false)
  expect(screen.getByRole('button',{name:'Return to flight position'})).toBeVisible()
  fireEvent.keyDown(window,{code:'Escape',key:'Escape'});expect(onClose).toHaveBeenCalledOnce()
  view.unmount()
 })
})

it('preserves the selected progress but resets auto on Restart, and Defaults restores the original time',async()=>{
 const {runtime,instances,view}=await mount()
 const original=runtime.environmentClock.solarDayProgress
 runtime.weather.capture('light-rain');for(let i=0;i<2700;i++)runtime.weather.tick(1/60,clockPolicy('viewpoint'))
 const weatherBefore=runtime.weather.serialize()
 act(()=>{runtime.setSolarDayProgress(.7);runtime.setSolarMode('auto')})
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 fireEvent.click(screen.getByRole('tab',{name:'Views'}))
 fireEvent.click(screen.getByText('Choose a new starting point'))
 fireEvent.click(screen.getByRole('button',{name:'Start from Coast entrance'}))
 await waitFor(()=>expect(instances).toHaveLength(2))
 const restarted=instances[1]!
 expect(restarted.environmentClock.solarDayProgress).toBe(.7)
 expect(restarted.environmentClock.solarMode).toBe('fixed')
 expect(restarted.weather.snapshot().mode).toBe('fixed');expect(restarted.weather.snapshot().target).toBeNull()
 expect(restarted.weather.snapshot().resolved).toEqual(weatherBefore.resolved);expect(restarted.weather.snapshot().wetness).toBe(weatherBefore.wetness);expect(restarted.weather.snapshot().phase).toEqual(weatherBefore.phase)
 expect(runtime.running).toBe(false)
 await waitFor(()=>expect(restarted.pose.children).toHaveLength(1))
 act(()=>{restarted.update(0);restarted.completedFrame(document.createElement('canvas'))})
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 fireEvent.click(screen.getByText('Restore initial settings'))
 fireEvent.click(screen.getByRole('button',{name:'Restore defaults and restart'}))
 await waitFor(()=>expect(instances).toHaveLength(3))
 expect(instances[2]!.environmentClock.solarDayProgress).toBe(original)
 expect(instances[2]!.environmentClock.solarMode).toBe('fixed')
 expect(instances[2]!.weather.snapshot().resolved.coverage).toBe(0);expect(instances[2]!.weather.snapshot().wetness).toBe(0)
 view.unmount()
})

it('preserves automatic mode through a quality preparation but waits for explicit resume',async()=>{
 const {runtime,view}=await mount()
 act(()=>{runtime.start();runtime.setSolarDayProgress(.7);runtime.setSolarMode('auto')})
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 fireEvent.click(screen.getByRole('tab',{name:'Flight'}))
 const progress=runtime.environmentClock.solarDayProgress
 fireEvent.click(screen.getByText('Flight & display settings'))
 fireEvent.click(screen.getByRole('button',{name:'Standard'}))
 expect(runtime.getSnapshot().phase).toBe('buffering')
 expect(runtime.getSnapshot().daylight?.status).toBe('suspended')
 expect(runtime.environmentClock.solarMode).toBe('auto')
 act(()=>{runtime.update(0);runtime.completedFrame(document.createElement('canvas'))})
 expect(runtime.getSnapshot().phase).toBe('paused')
 expect(runtime.environmentClock.solarDayProgress).toBe(progress)
 act(()=>runtime.start());expect(runtime.getSnapshot().daylight?.status).toBe('running')
 view.unmount()
})

it('changes weather live, isolates the two automatic modes and preserves pending weather while paused',async()=>{
 const {runtime,instances,view}=await mount()
 act(()=>runtime.start())
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 fireEvent.click(screen.getByRole('button',{name:'Auto'}))
 fireEvent.click(screen.getByText('Let the weather change'))
 fireEvent.click(screen.getByRole('switch',{name:'Automatic weather'}))
 expect(runtime.weather.snapshot().mode).toBe('auto')
 fireEvent.click(screen.getByRole('button',{name:'Light rain'}))
 expect(runtime.weather.snapshot().mode).toBe('fixed');expect(runtime.weather.snapshot().target).toBe('light-rain')
 expect(runtime.environmentClock.solarMode).toBe('auto');expect(runtime.getSnapshot().phase).toBe('flying');expect(instances).toHaveLength(1)
 act(()=>runtime.pause('user'))
 const resolved=runtime.weather.snapshot().resolved
 fireEvent.click(screen.getByRole('button',{name:'Overcast'}))
 act(()=>runtime.update(60))
 expect(runtime.weather.snapshot().resolved).toEqual(resolved)
 expect(screen.getByText('Resume flight or scenery for the weather to change.')).toBeVisible()
 const key=vi.spyOn(runtime.input,'key');fireEvent.keyDown(screen.getByRole('button',{name:'Overcast'}),{code:'ArrowRight',key:'ArrowRight'});expect(key).not.toHaveBeenCalled()
 view.unmount()
})

it('keeps Nature opt-in, cards paused, photos nonmodal and Restart visually consistent',async()=>{
 const {runtime,view,instances}=await mount()
 act(()=>runtime.start())
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 expect(screen.getByRole('switch',{name:'Vegetation breeze'})).not.toBeChecked()
 expect(runtime.soundscape.getSnapshot().enabled).toBe(false)
 fireEvent.click(screen.getByRole('switch',{name:'Vegetation breeze'}))
 expect(runtime.getSnapshot().phase).toBe('flying')
 fireEvent.click(screen.getByRole('button',{name:'Take a postcard'}))
 expect(runtime.getSnapshot().phase).toBe('flying')
 expect(runtime.photos.getSnapshot().status).toBe('waiting')
 expect(screen.queryByRole('tab')).toBeNull()
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 const mute=vi.spyOn(runtime.soundscape,'setMuted')
 fireEvent.click(screen.getByRole('tab',{name:'Views'}))
 fireEvent.click(screen.getByText('Look a little closer'))
 fireEvent.click(screen.getByRole('button',{name:/Light on water/}))
 expect(runtime.getSnapshot().phase).toBe('paused');expect(mute).toHaveBeenCalledWith(true)
 act(()=>{runtime.start();runtime.update(1/60)})
 expect(runtime.getSnapshot().phase).toBe('paused')
 fireEvent.click(screen.getByRole('button',{name:'Close and stay paused'}))
 expect(runtime.getSnapshot().phase).toBe('paused')
 expect(screen.getByRole('button',{name:/Light on water/})).toHaveFocus()
 fireEvent.click(screen.getByRole('tab',{name:'Views'}))
 fireEvent.click(screen.getByText('Choose a new starting point'))
 fireEvent.click(screen.getByRole('button',{name:'Start from Coast entrance'}))
 await waitFor(()=>expect(instances).toHaveLength(2))
 expect(instances[1]!.livingIntent.wind).toBe(true)
 expect(instances[1]!.soundscape.getSnapshot().enabled).toBe(false)
 expect(runtime.photos.getSnapshot().photos).toHaveLength(0)
 view.unmount()
})

it('cancels a waiting photo when viewpoint preparation replaces its intended frame',async()=>{
 const {runtime,view}=await mount()
 expect(runtime.requestPhoto()).toBe(true)
 act(()=>runtime.enterViewpoint('seaward'))
 const complete=vi.spyOn(runtime.photos,'completedFrame')
 act(()=>runtime.completedFrame(document.createElement('canvas')))
 expect(complete).not.toHaveBeenCalled()
 expect(runtime.photos.getSnapshot().status).toBe('idle')
 view.unmount()
})

it('groups scenery into three purpose tabs and reveals notes only by choice without stopping travel',async()=>{
 const {runtime,view}=await mount()
 act(()=>runtime.start())
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 expect(screen.getAllByRole('tab')).toHaveLength(3)
 expect(screen.getByRole('tab',{name:'Scenery'})).toHaveAttribute('aria-selected','true')
 expect(screen.getByRole('button',{name:'Auto'})).toBeVisible()
 expect(screen.getByRole('button',{name:'Light rain'})).toBeVisible()
 expect(screen.getByRole('switch',{name:'Vegetation breeze'}).parentElement).toBeVisible()
 expect(screen.queryByRole('button',{name:/Light on water/})).toBeNull()
 const input=vi.spyOn(runtime.input,'key')
 fireEvent.keyDown(screen.getByRole('tab',{name:'Scenery'}),{key:'ArrowRight',code:'ArrowRight'})
 expect(screen.getByRole('tab',{name:'Views'})).toHaveFocus()
 expect(input).not.toHaveBeenCalled()
 expect(runtime.getSnapshot().phase).toBe('flying')
 expect(screen.getByRole('button',{name:/Light on water/})).not.toBeVisible()
 fireEvent.click(screen.getByText('Look a little closer'))
 expect(screen.getByRole('button',{name:/Light on water/})).toBeVisible()
 expect(runtime.getSnapshot().phase).toBe('flying')
 expect(document.querySelector('.flight-settings-scroll .flight-settings-body')).not.toBeNull()
 expect(document.querySelector('.flight-settings-scroll-shell .museum-scrollbar-visual')).not.toBeNull()
 view.unmount()
})


it('dismisses postcards before flight when Escape comes from outside the gallery',async()=>{
 const {runtime,view,onClose}=await mount()
 act(()=>runtime.start())
 const pocket=screen.getByRole('button',{name:'View postcards, 0'})
 fireEvent.click(pocket)
 expect(screen.getByRole('button',{name:'Close postcards'})).toHaveFocus()
 const pause=screen.getByRole('button',{name:'Stop and look'})
 pause.focus()
 fireEvent.keyDown(pause,{key:'Escape',code:'Escape'})
 expect(screen.queryByRole('button',{name:'Close postcards'})).toBeNull()
 expect(pocket).toHaveFocus()
 expect(onClose).not.toHaveBeenCalled()
 expect(runtime.getSnapshot().phase).toBe('flying')
 fireEvent.keyDown(pocket,{key:'Escape',code:'Escape'})
 expect(onClose).toHaveBeenCalledOnce()
 view.unmount()
})

it('keeps a completed still and a global return command available across settings tabs during viewpoint preparation',async()=>{
 const {runtime,view}=await mount()
 act(()=>runtime.start())
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 // Language belongs to the panel shell, independently of the selected section.
 expect(screen.getByRole('button',{name:'Change language, current English'})).toBeVisible()
 fireEvent.click(screen.getByRole('tab',{name:'Views'}))
 fireEvent.click(screen.getByRole('button',{name:'Out to sea Look beyond the shore'}))
 expect(runtime.observation.phase).toBe('inactive')
 const frame=document.createElement('canvas');frame.width=1600;frame.height=900
 act(()=>runtime.completedFrame(frame))
 expect(runtime.observation.phase).toBe('preparing')
 const still=runtime.viewTransition.canvas
 expect(still).not.toBeNull();expect(document.querySelector('.flight-view-still canvas')).toBe(still)
 fireEvent.click(screen.getByRole('tab',{name:'Flight'}))
 expect(screen.queryByRole('group',{name:'Starting place'})).not.toBeInTheDocument()
 fireEvent.click(screen.getByRole('button',{name:'Back to flight'}))
 expect(runtime.observation.phase).toBe('returning');expect(runtime.viewTransition.canvas).toBe(still)
 expect(screen.getByRole('button',{name:'Back to flight'})).toBeDisabled()
 expect(runtime.getSnapshot().phase).toBe('paused')
 view.unmount();expect(still?.width).toBe(0)
})


it.each(['ready','paused'] as const)('quiet viewing dismisses the %s card and retains one working flight action',async(phase)=>{
 const {runtime,view,onClose}=await mount()
 if(phase==='paused')act(()=>{runtime.start();runtime.setFocusState(false);runtime.setFocusState(true)})
 const position={...runtime.simulation.position}
 fireEvent.click(screen.getByRole('button',{name:'Just look at the scenery'}))
 expect(document.querySelector('.flight-intro')).toBeNull()
 expect(screen.queryByRole('button',{name:'Just look at the scenery'})).toBeNull()
 act(()=>runtime.update(1/60))
 expect(runtime.simulation.position).toEqual(position)
 fireEvent.click(screen.getByRole('button',{name:phase==='ready'?'Start flying':'Continue flying'}))
 expect(runtime.getSnapshot().phase).toBe('flying')
 expect(onClose).not.toHaveBeenCalled()
 view.unmount()
})

it('closes the museum language menu before the flight card, restoring focus in order',async()=>{
 const {view,onClose}=await mount()
 fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
 const language=screen.getByRole('button',{name:'Change language, current English'})
 fireEvent.click(language)
 fireEvent.keyDown(screen.getByRole('menuitemradio',{name:'English'}),{key:'Escape',code:'Escape'})
 await waitFor(()=>expect(language).toHaveFocus())
 expect(screen.queryByRole('menu')).toBeNull()
 expect(screen.getByRole('tab',{name:'Scenery'})).toBeVisible()
 fireEvent.keyDown(language,{key:'Escape',code:'Escape'})
 expect(screen.queryByRole('tab',{name:'Scenery'})).toBeNull()
 expect(onClose).not.toHaveBeenCalled()
 view.unmount()
})

it('keeps failure controls awake after quiet viewing and avoids duplicate start actions',async()=>{
 const {runtime,view}=await mount()
 vi.useFakeTimers()
 try {
  fireEvent.click(screen.getByRole('button',{name:'Just look at the scenery'}))
  fireEvent.click(screen.getByRole('button',{name:'Flight & scenery'}))
  expect(screen.getAllByRole('button',{name:'Start flying'})).toHaveLength(1)
  fireEvent.keyDown(window,{key:'Escape',code:'Escape'})
  vi.spyOn(console,'error').mockImplementation(()=>{})
  act(()=>runtime.fail(new Error('injected quiet-view fault')))
  act(()=>{vi.advanceTimersByTime(5000)})
  expect(screen.getByRole('alert')).toBeVisible()
  expect(screen.getByRole('dialog')).toHaveAttribute('data-hud-idle','false')
 } finally {view.unmount();vi.useRealTimers()}
})
